contents/docs/samples/index.mdx
Link was pointing to the non DO source code
=> Fix: do sample source code link

contents/docs/react/index.mdx
Current React.js example has missing import in it
=> Fix React.js example code

contents/docs/postgres-support/index.mdx
The current example uses some old format for relationships. This fixes it and makes the whole example more useful.
=> Better example for Self-Referential Relationships

contents/docs/release-notes/0.1/index.mdx, contents/docs/release-notes/0.3/index.mdx, contents/docs/release-notes/0.6/index.mdx, contents/docs/release-notes/0.7/index.mdx, contents/docs/zero-schema/index.mdx
broken links surfaced by https://github.com/rocicorp/zero-docs/pull/47
The only important one was in contents/docs/zero-schema/index.mdx
=> fix some broken links

contents/docs/postgres-support/index.mdx, contents/docs/zero-schema/index.mdx
Recursive relationships not being under the `schema` section of the docs is a bit odd.
https://discord.com/channels/830183651022471199/1325235004674150484/1325235007987384472 & https://discord.com/channels/830183651022471199/1324865498130944011/1325368342449618974
=> move recursive schema docs, fix typos

contents/docs/writing-data/index.mdx
Hi! Here's a small typo fix for the docs.
The code examples set the `language` field, but the comments erroneously refer to a `nickname` field.
=> Fix small typo: nickname/language

contents/docs/deployment/index.mdx
The specification of the port is specific to the routing method. With internal load balancing, for example, it should not be included.
=> doc: remove port from replication-manager url

components/hooks/useHash.ts, components/toc.tsx, components/ui/ActiveHashLink.tsx
While using the Zero documentation, I encountered several usability issues with the right-side navigation bar that could impact the reading experience.
1. **Non-scrollable Right Bar**
- The right navigation bar lacks scrolling functionality
- Some navigation elements can be cut off or hidden when they extend beyond the viewport
2. **Missing Active Link Highlighting**
- Currently active/matched links don't have visual indicators
- Makes it difficult to track your current position in the documentation
3. **Browser History Navigation Issues**
- When using browser back/forward buttons
- The matched link doesn't automatically scroll into view
- Users need to manually locate their position
This PR aims to enhance the documentation navigation experience by:
- Adding proper scroll behavior to the …
=> feature: made toc aside scrollable, add matched state for link

contents/docs/quickstart/index.mdx
Hi! I'm new to Zero and just spun up the hello-zero via quickstart instructions.
I think this docs change is correct to bring this docs repo in line with the hello-zero repo:
Fix quickstart docs to reflect recent change in hello-zero: https://github.com/rocicorp/hello-zero/commit/5bfc4ba7648fb12ef2861ccc7bfa7d1c49d51e29
=> hello-zero uses one pg db

contents/docs/permissions.mdx
The zbugs permissions example link was broken. This commit fixes it by pointing to the correct location of the zbugs schema file at the line where the permissions definition for zbugs begins.
=> Fix broken link to zbugs permissions

contents/docs/add-to-existing-project.mdx
Since it  returns [] unless there has been a preload which we are not going into here.
=> docs: Remove run() from the read data section

contents/docs/debug/inspector.mdx
To make it clearer that it should be used with lazy loading.
https://bugs.rocicorp.dev/issue/3699
=> docs: Update inspector documentation

contents/docs/custom-mutators.mdx, contents/docs/debug/slow-queries.mdx, contents/docs/deployment.mdx, contents/docs/permissions.mdx, contents/docs/reading-data.mdx, contents/docs/writing-data.mdx, contents/docs/zero-schema.mdx
Found some typos as well as broken code examples when reading through.
=> docs: fix various typos and code errors

contents/docs/add-to-existing-project.mdx, contents/docs/quickstart.mdx
I was trying out Zero and noticed that the quickstart section instructs the person onboarding to add the trusted deps to their package json, but the quickstart repo already has this. this section makes the intro feel noisy. 
trusted deps were added in this pr https://github.com/rocicorp/hello-zero/pull/23
=> chore: remove trusted deps section

components/leftbar.tsx
To fix scrolling problem on very small displays on views where the main body content is shorter than the left sidebar.
=> fix: Removing calculated height of left bar

contents/docs/solidjs.mdx
These docs changes follow the API changes introduced in https://github.com/rocicorp/mono/pull/4474.
=> Updated solid docs with context-dependent APIs

contents/docs/connecting-to-postgres.mdx
Headings were not properly indented under [Provider-Specific Notes](https://zero.rocicorp.dev/docs/connecting-to-postgres#provider-specific-notes)
=> fix: Connecting to Postgres headings hierarchy 

assets/search-index.json, components/search.tsx, lib/generateSearchIndex.ts, package-lock.json, package.json
The change to the stringified markdown was not including code blocks. This fixes that with https://github.com/remarkjs/strip-markdown
=> fix: updated the search index to include code blocks

contents/docs/deployment.mdx
* Use the `ZERO_CHANGE_STREAMER_URI` and load balancer as the recommended service discovery mechanism
* Add the `healthCheckGracePeriodSeconds` to the example, as this trips up a lot of people with large databases
* Remove the inter-service "wait" dependency; it is no longer needed as of 0.22 (https://github.com/rocicorp/mono/pull/4658)
=> chore: update sst deployment example

contents/docs/deployment.mdx
This essentially reverts the CHANGE_STREAMER_MODE change in 0.20 (https://github.com/rocicorp/zero-docs/commit/a21767436563cbda9385366299ea3c7e4fbc2de0)
=> chore: update raw aws docs back to CHANGE_STREAMER_URI

contents/docs/roadmap.mdx
Reading "late this year or early next", I had to pause for a second and do the mental maths of _do they mean late 2025 and early 2026, or are they behind schedule (as happens in software development) and meant early 2025?_.
It is a nit-picky change, but I think numerical years communicate the timeline the clearest. Especially for people who might not be as familiar with Zero.
=> refactor: use explicit year numbers
